# Generated by Django 4.1.1 on 2022-10-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_item_pic_2_product_item_pic_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rent_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rent_to',
            field=models.DateField(null=True),
        ),
    ]
