# Generated by Django 4.1.1 on 2022-10-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_order_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_list',
        ),
    ]
