# Generated by Django 4.1.1 on 2022-10-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_product_item_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
